project_name: crop-prediction-ml
data:
  raw_data_path: data/raw
  processed_data_path: data/processed
  
model:
  random_seed: 42
  test_size: 0.2
  
feature_selection:
  methods:
    - mutual_info
    - f_classif
    - chi2